version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wefin-postgres
    environment:
      POSTGRES_DB: wefin_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wefin-network

volumes:
  postgres_data:

networks:
  wefin-network:
    driver: bridge
