openapi: 3.0.3
info:
  title: API WEFIN
  description: Sistema de Conversão de produtos e moedas
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor de desenvolvimento

paths:
  # REINO ENDPOINTS
  /reino:
    get:
      tags:
        - Controller Reino
      summary: Buscar todos os reinos
      operationId: todosReinos
      responses:
        '200':
          description: Lista de reinos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReinoResponse'
    post:
      tags:
        - Controller Reino
      summary: Criar reino
      operationId: criarReino
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReinoRequest'
      responses:
        '201':
          description: Reino criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReinoResponse'

  /reino/{id}:
    get:
      tags:
        - Controller Reino
      summary: Buscar reino por id
      operationId: buscarReino
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Reino encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReinoResponse'
    put:
      tags:
        - Controller Reino
      summary: Atualizar reino
      operationId: atualizarReino
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReinoRequest'
      responses:
        '200':
          description: Reino atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReinoResponse'
    delete:
      tags:
        - Controller Reino
      summary: Deletar reino
      operationId: deletarReino
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Reino deletado

  # MOEDA ENDPOINTS
  /moeda:
    get:
      tags:
        - Controller Moeda
      summary: Buscar todas as moedas
      operationId: todasMoedas
      responses:
        '200':
          description: Lista de moedas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoedaResponse'
    post:
      tags:
        - Controller Moeda
      summary: Criar moeda
      operationId: criarMoeda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoedaRequest'
      responses:
        '201':
          description: Moeda criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoedaResponse'

  /moeda/{id}:
    get:
      tags:
        - Controller Moeda
      summary: Buscar moeda por id
      operationId: buscarMoeda
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Moeda encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoedaResponse'
    put:
      tags:
        - Controller Moeda
      summary: Atualizar moeda
      operationId: atualizarMoeda
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoedaRequest'
      responses:
        '200':
          description: Moeda atualizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoedaResponse'
    delete:
      tags:
        - Controller Moeda
      summary: Deletar moeda
      operationId: deletarMoeda
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Moeda deletada

  /moeda/{sigla}/taxa_cambio:
    post:
      tags:
        - Controller Moeda
      summary: Criar taxa de cambio
      operationId: criarTaxaCambio
      parameters:
        - name: sigla
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaxaCambioRequest'
      responses:
        '201':
          description: Taxa de cambio criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxaCambioResponse'

  /moeda/{sigla}/taxas:
    get:
      tags:
        - Controller Moeda
      summary: Buscar todas as taxas de uma moeda
      operationId: buscarTodasTaxas
      parameters:
        - name: sigla
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de taxas de cambio
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxaCambioResponse'

  /moeda/{sigla}/converter:
    get:
      tags:
        - Controller Moeda
      summary: Fazer conversão de moeda
      operationId: conversaoMoeda
      parameters:
        - name: sigla
          in: path
          required: true
          schema:
            type: string
        - name: moedaDestinoSigla
          in: query
          required: true
          schema:
            type: string
        - name: valor
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Conversão realizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MoedaConversaoDTO'

  # PRODUTO ENDPOINTS
  /produto:
    get:
      tags:
        - Controller Produto
      summary: Buscar todos os produtos
      operationId: todosProdutos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProdutoResponse'
    post:
      tags:
        - Controller Produto
      summary: Criar produto
      operationId: criarProduto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoRequest'
      responses:
        '201':
          description: Produto criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoResponse'

  /produto/{id}:
    get:
      tags:
        - Controller Produto
      summary: Buscar produto por id
      operationId: buscarProduto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoResponse'
    put:
      tags:
        - Controller Produto
      summary: Atualizar produto
      operationId: atualizarProduto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProdutoRequest'
      responses:
        '200':
          description: Produto atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoResponse'
    delete:
      tags:
        - Controller Produto
      summary: Deletar produto
      operationId: deletarProduto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Produto deletado

  /produto/{id}/converter:
    get:
      tags:
        - Controller Produto
      summary: Fazer conversão do produto para outra moeda
      operationId: conversaoProduto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: moedaDestinoSigla
          in: query
          required: true
          schema:
            type: string
        - name: valor
          in: query
          required: true
          schema:
            type: number
        - name: quantidade
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Conversão realizada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProdutoConversaoDTO'

  # TRANSACAO ENDPOINTS
  /transacao:
    post:
      tags:
        - Controller Transacao
      summary: Criar transação
      operationId: criarTransacao
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransacaoRequest'
      responses:
        '201':
          description: Transação criada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransacaoResponse'

components:
  schemas:
    # REQUEST SCHEMAS
    ReinoRequest:
      type: object
      required:
        - nome
      properties:
        nome:
          type: string
          description: Nome do reino
          example: "Reino de Asgard"

    MoedaRequest:
      type: object
      required:
        - nome
        - sigla
        - reinoOrigem
      properties:
        nome:
          type: string
          maxLength: 50
          description: Nome da moeda
          example: "Ouro de Asgard"
        sigla:
          type: string
          minLength: 1
          maxLength: 6
          description: Sigla da moeda
          example: "ASG"
        reinoOrigem:
          type: integer
          format: int64
          description: ID do reino de origem
          example: 1

    ProdutoRequest:
      type: object
      required:
        - nome
        - moeda
      properties:
        nome:
          type: string
          description: Nome do produto
          example: "Espada Élfica"
        moeda:
          type: string
          description: Sigla da moeda de origem do produto
          example: "ASG"

    TransacaoRequest:
      type: object
      properties:
        produto:
          type: integer
          format: int64
          description: ID do produto
          example: 1
        valorOrigem:
          type: number
          format: double
          description: Valor original da transação
          example: 100.50
        valorConvertido:
          type: number
          format: double
          description: Valor convertido da transação
          example: 150.75
        taxaCambio:
          type: integer
          format: int64
          description: ID da taxa de câmbio
          example: 1

    TaxaCambioRequest:
      type: object
      required:
        - moedaDestino
        - taxa
      properties:
        moedaDestino:
          type: string
          description: Sigla da moeda de destino
          example: "ELF"
        taxa:
          type: number
          format: double
          description: Taxa de câmbio
          example: 1.5

    ConversaoMoedaRequest:
      type: object
      required:
        - valor
        - moedaDestinoSigla
      properties:
        valor:
          type: number
          format: double
          minimum: 0.01
          description: Valor a ser convertido
          example: 100.00
        moedaDestinoSigla:
          type: string
          description: Sigla da moeda de destino para conversão
          example: "ELF"

    ConversaoProdutoRequest:
      type: object
      required:
        - valor
        - quantidade
        - moedaDestinoSigla
      properties:
        valor:
          type: number
          format: double
          minimum: 0.01
          description: Valor do produto
          example: 50.00
        quantidade:
          type: integer
          minimum: 1
          description: Quantidade do produto
          example: 2
        moedaDestinoSigla:
          type: string
          description: Sigla da moeda de destino para conversão
          example: "ELF"

    # RESPONSE SCHEMAS
    ReinoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID do reino
          example: 1
        nome:
          type: string
          description: Nome do reino
          example: "Reino de Asgard"

    MoedaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da moeda
          example: 1
        nome:
          type: string
          description: Nome da moeda
          example: "Ouro de Asgard"
        sigla:
          type: string
          description: Sigla da moeda
          example: "ASG"
        reinoOrigem:
          $ref: '#/components/schemas/ReinoResponse'

    ProdutoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID do produto
          example: 1
        nome:
          type: string
          description: Nome do produto
          example: "Espada Élfica"
        moeda:
          $ref: '#/components/schemas/MoedaResponse'

    TaxaCambioResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da taxa de câmbio
          example: 1
        moedaOrigem:
          $ref: '#/components/schemas/MoedaResponse'
        moedaDestino:
          $ref: '#/components/schemas/MoedaResponse'
        taxa:
          type: number
          format: double
          description: Taxa de câmbio
          example: 1.5
        dataHora:
          type: string
          format: date-time
          description: Data e hora da criação da taxa
          example: "25-05-2024 14:30:00"

    TransacaoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID da transação
          example: 1
        produto:
          $ref: '#/components/schemas/ProdutoResponse'
        valorOrigem:
          type: number
          format: double
          description: Valor original da transação
          example: 100.50
        valorConvertido:
          type: number
          format: double
          description: Valor convertido da transação
          example: 150.75
        taxaCambio:
          $ref: '#/components/schemas/TaxaCambioResponse'
        dataHora:
          type: string
          format: date-time
          description: Data e hora da transação
          example: "25-05-2024 14:30:00"
        reinoOrigem:
          $ref: '#/components/schemas/ReinoResponse'

    MoedaConversaoDTO:
      type: object
      properties:
        valorOrigem:
          type: number
          format: double
          description: Valor original
          example: 100.00
        valorConvertido:
          type: number
          format: double
          description: Valor convertido
          example: 150.00
        taxa:
          $ref: '#/components/schemas/TaxaCambioResponse'
        origemDestinoDesc:
          type: string
          description: Descrição da conversão
          example: "100.00 'ASG' = 150.00 'ELF'"

    ProdutoConversaoDTO:
      type: object
      properties:
        produto:
          $ref: '#/components/schemas/ProdutoResponse'
        valorOrigem:
          type: number
          format: double
          description: Valor original
          example: 100.00
        valorConvertido:
          type: number
          format: double
          description: Valor convertido
          example: 150.00
        taxa:
          $ref: '#/components/schemas/TaxaCambioResponse'
        origemDestinoDesc:
          type: string
          description: Descrição da conversão
          example: "100.00 'ASG' = 150.00 'ELF'"